kind: pipeline
name: default

volumes:
  - name: cache
    temp: {}

steps:
  - name: build_ui_dev
    image: plugins/docker
    volumes:
      - name: cache
        path: /var/lib/docker
    settings:
      tags:
        - "${DRONE_COMMIT_SHA:0:7}_dev-env"
        - dev-env
      target: dev
      context: ui
      dockerfile: ui/Dockerfile
      repo: uccnetsoc/cloud-ui
      registry: docker.io
      custom_dns: [1.1.1.1]
      username:
        from_secret: docker_hub_user
      password:
        from_secret: docker_hub_token
    when:
      event:
        - push
      branch:
        - master

  - name: build_ui_prod
    image: plugins/docker
    volumes:
      - name: cache
        path: /var/lib/docker
    settings:
      tags:
        - "${DRONE_COMMIT_SHA:0:7}"
        - latest
      context: ui
      target: prod
      dockerfile: ui/Dockerfile
      repo: uccnetsoc/cloud-ui
      registry: docker.io
      custom_dns: [1.1.1.1]
      username:
        from_secret: docker_hub_user
      password:
        from_secret: docker_hub_token
    when:
      event:
        - push
      branch:
        - master

  - name: build_api_dev
    image: plugins/docker
    volumes:
      - name: cache
        path: /var/lib/docker
    settings:
      tags:
        - "${DRONE_COMMIT_SHA:0:7}_dev-env"
        - dev-env
      target: dev
      context: api
      dockerfile: api/Dockerfile
      repo: uccnetsoc/cloud-api
      registry: docker.io
      custom_dns: [1.1.1.1]
      username:
        from_secret: docker_hub_user
      password:
        from_secret: docker_hub_token
    when:
      event:
        - push
      branch:
        - master

  - name: build_api_prod
    image: plugins/docker
    volumes:
      - name: cache
        path: /var/lib/docker
    settings:
      tags:
        - "${DRONE_COMMIT_SHA:0:7}"
        - latest
      target: prod
      context: api
      dockerfile: api/Dockerfile
      repo: uccnetsoc/cloud-api
      registry: docker.io
      custom_dns: [1.1.1.1]
      username:
        from_secret: docker_hub_user
      password:
        from_secret: docker_hub_token
    when:
      event:
        - push
      branch:
        - master
        
  - name: clone_nac
    image: docker:git
    commands:
      - git clone https://github.com/UCCNetsoc/NaC.git .ansible
      - mkdir -p ./keys/infra/web/
      - printf '%s\n' "$KEY_WEB" >./keys/infra/web/id_rsa
      - chmod 0600 ./keys/infra/web/id_rsa
      - ls -al ./keys/infra/web
    environment:
      KEY_WEB:
        from_secret: key_web
        
  - name: ansible_deploy
    image: uccnetsoc/drone-ansible
    environment:
      PM_HOST: '10.0.30.53'
      PM_USER:
        from_secret: proxmox_user
      PM_PASS:
        from_secret: proxmox_pass
      VAULT_PASS:
        from_secret: vault_pass
    settings:
      playbook: .ansible/provision-infra-web.yml
      requirements: .ansible/requirements.txt
      inventory: .ansible/proxmox_inventory.py
      private_key:
        from_secret: key_web
      vault_password:
        from_secret: vault_pass
      tags:
        - netsoc-cloud

  - name: discord_notif_success
    image: appleboy/drone-discord
    environment:
      WEBHOOK_ID:
        from_secret: discord_webhook_id
      WEBHOOK_TOKEN:
        from_secret: discord_webhook_token
    settings:
      username: Netsoc CI
      avatar_url: https://raw.githubusercontent.com/drone/brand/3051b0d85318a2a20b62927ba19fc07e24c0d751/logos/png/white/drone-logo-png-white-256.png
      color: "#42f483"
      message: Cloud successfully built and pushed. Build num {{build.number}}. {{build.link}}
    when:
      event:
        - push
      branch:
        - master
      status:
        - success

  - name: discord_notif_failure
    image: appleboy/drone-discord
    environment:
      WEBHOOK_ID:
        from_secret: discord_webhook_id
      WEBHOOK_TOKEN:
        from_secret: discord_webhook_token
    settings:
      username: Netsoc CI
      avatar_url: https://raw.githubusercontent.com/drone/brand/3051b0d85318a2a20b62927ba19fc07e24c0d751/logos/png/white/drone-logo-png-white-256.png
      color: "#e04414"
      message: Cloud failed for {{build.author}}. Build num {{build.number}}. {{build.link}}
    when:
      event:
        - push
      branch:
        - master
      status:
        - failure

---
kind: secret
name: discord_webhook_id
get:
  path: discord/sysadmins_webhook
  name: discord_webhook_id

---
kind: secret
name: discord_webhook_token
get:
  path: discord/sysadmins_webhook
  name: discord_webhook_token

---
kind: secret
name: docker_hub_user
get:
  path: docker_registry/docker_hub
  name: docker_hub_user

---
kind: secret
name: docker_hub_token
get:
  path: docker_registry/docker_hub
  name: docker_hub_token

---
kind: secret
name: github_token
get:
  path: github/personal_access_tokens
  name: public_repo_token
