version: "3.7"
services:
  admin.netsoc.local:
    build:
      context: "./ui"
      target: dev
    command: npm run serve
    volumes:
      - "./ui/:/app"
    environment:
      VUE_APP_NETSOC_API_URL: "http://api.netsoc.local"
      VUE_APP_OIDC_AUTHORITY: http://keycloak.netsoc.local:8080/auth/realms/freeipa
  api.netsoc.local:
    restart: always
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
    volumes:
      - "./api/v1:/app/v1/"
      - "./api/requirements.txt:/requirements.txt"
      - "./api/prestart.sh:/app/prestart.sh"
      - "./config.sample.yml:/config.yml"
      - "./home/users/:/home/users:Z"
    command: /start-reload.sh --host 0.0.0.0 --port 8080
    environment:
      MODULE_NAME: "v1.main"  
      VARIABLE_NAME: "api"
  unitproxy.netsoc.local:
    image: nginx:1.19.2
    depends_on:
      - "unit.netsoc.local"
    volumes:
      - "./unitproxy.nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./unitproxy.htpasswd:/unitproxy.htpasswd:ro"
      - "./unitproxy-fix-socket-permissions.sh:/docker-entrypoint.d/fix-socket-permssions.sh"
      - "unitsock:/var/run/:z"
  unit.netsoc.local:
    privileged: true
    cap_add:
      - ALL
    entrypoint: /usr/sbin/unitd --no-daemon --control unix:/var/run/control.unit.sock
    image: nginx/unit:1.19.0-full
    volumes:
      - "./home/users/:/home/users/:z"
      - "unitsock:/var/run/:z"
  ipa.netsoc.local:
    image: uccnetsoc/freeipa-server:4.8.7-pulled-2020-07-03
    command: >
      ipa-server-install
      --unattended
      --realm=netsoc.local
      --ds-password=netsoc_freeipa
      --admin-password=netsoc_freeipa
      --no-host-dns
    hostname: ipa.netsoc.local
    read_only: true
    environment:
      IPA_SERVER_HOSTNAME: ipa.netsoc.local
    tmpfs:
      - "/run"
      - "/tmp"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "/etc/machine-id:/etc/machine-id:ro"
      - "./backing-services/freeipa/data:/data:z"
    sysctls:
      #  Fixes:
      #  DEBUG The ipa-server-install command failed, exception: 
      #  RuntimeError: IPv6 stack is enabled in the kernel but there is no interface that has ::1 address assigned.
      #  Add ::1 address resolution to "lo" interface. You might need to enable IPv6 on the interface "lo" in sysctl.conf.
      net.ipv6.conf.lo.disable_ipv6: 0
  ipaclient.netsoc.local:
    hostname: ipaclient.netsoc.local
    image: adelton/freeipa-client
    restart: always
    depends_on:
      - "ipa.netsoc.local"
    environment:
      PASSWORD: netsoc_freeipa
      IPA_CLIENT_INSTALL_OPTS: --server=ipa.netsoc.local --domain=netsoc.local --force-join
    volumes:
      - "./home/:/home/:Z"
  keycloak.netsoc.local:
    image: uccnetsoc/keycloak:9.0.3-themed
    environment:
      KEYCLOAK_USER: netsoc_keycloak
      KEYCLOAK_PASSWORD: netsoc_keycloak
      KEYCLOAK_IMPORT: /tmp/keycloak/freeipa-realm.json
      DB_VENDOR: H2
    depends_on:
      - "ipa.netsoc.local"
    hostname:
      keycloak.netsoc.local
    volumes:
      - "./backing-services/keycloak/:/tmp/keycloak/"
      - "./backing-services/keycloak/krb5.keytab:/krb5.keytab"
      - "/etc/localtime:/etc/localtime:ro"
  mysql.netsoc.local:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: netsoc_mysql
    ports:
      - "0.0.0.0:3306:3306"
  proxy.netsoc.local:
    image: wernight/dante
    ports:
      - "0.0.0.0:1080:1080"
  whoami.netsoc.local:
    image: containous/whoami
volumes:
  unitsock: