# This is a basic workflow to help you get started with Actions

name: Beta CI

concurrency:
    group: ci
    cancel-in-progress: true

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ beta ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Builds docker images and pushes them to GHCR
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push API dev-env image
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          context: api
          tags: ghcr.io/uccnetsoc/cloud-api:beta-dev-env, ghcr.io/uccnetsoc/cloud-api:${{ github.sha }}-beta-dev-env
          target: dev

      - name: Build and push API prod image
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          context: api
          tags: ghcr.io/uccnetsoc/cloud-api:beta, ghcr.io/uccnetsoc/cloud-api:beta-${{ github.sha }}
          
      - name: Build and push UI dev-env image
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          context: ui
          tags: ghcr.io/uccnetsoc/cloud-ui:beta-dev-env, ghcr.io/uccnetsoc/cloud-ui:${{ github.sha }}-beta-dev-env
          target: dev

      - name: Build and push UI prod image
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          context: ui
          tags: ghcr.io/uccnetsoc/cloud-ui:beta, ghcr.io/uccnetsoc/cloud-ui:beta-${{ github.sha }}